//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: api.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Com_Example_GreeterClient`, then call methods of this protocol to make API calls.
public protocol Com_Example_GreeterClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? { get }

  func sayHello(
    _ request: Com_Example_HelloRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Example_HelloRequest, Com_Example_HelloReply>
}

extension Com_Example_GreeterClientProtocol {
  public var serviceName: String {
    return "com.example.Greeter"
  }

  /// Unary call to SayHello
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func sayHello(
    _ request: Com_Example_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Example_HelloRequest, Com_Example_HelloReply> {
    return self.makeUnaryCall(
      path: Com_Example_GreeterClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Com_Example_GreeterClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Com_Example_GreeterNIOClient")
public final class Com_Example_GreeterClient: Com_Example_GreeterClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the com.example.Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Com_Example_GreeterNIOClient: Com_Example_GreeterClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol?

  /// Creates a client for the com.example.Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Example_GreeterAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? { get }

  func makeSayHelloCall(
    _ request: Com_Example_HelloRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Example_HelloRequest, Com_Example_HelloReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Example_GreeterAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Example_GreeterClientMetadata.serviceDescriptor
  }

  public var interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSayHelloCall(
    _ request: Com_Example_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Example_HelloRequest, Com_Example_HelloReply> {
    return self.makeAsyncUnaryCall(
      path: Com_Example_GreeterClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Example_GreeterAsyncClientProtocol {
  public func sayHello(
    _ request: Com_Example_HelloRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Example_HelloReply {
    return try await self.performAsyncUnaryCall(
      path: Com_Example_GreeterClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Com_Example_GreeterAsyncClient: Com_Example_GreeterAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Example_GreeterClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Com_Example_GreeterClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'sayHello'.
  func makeSayHelloInterceptors() -> [ClientInterceptor<Com_Example_HelloRequest, Com_Example_HelloReply>]
}

public enum Com_Example_GreeterClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Greeter",
    fullName: "com.example.Greeter",
    methods: [
      Com_Example_GreeterClientMetadata.Methods.sayHello,
    ]
  )

  public enum Methods {
    public static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/com.example.Greeter/SayHello",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Com_Example_GreeterProvider: CallHandlerProvider {
  var interceptors: Com_Example_GreeterServerInterceptorFactoryProtocol? { get }

  func sayHello(request: Com_Example_HelloRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Example_HelloReply>
}

extension Com_Example_GreeterProvider {
  public var serviceName: Substring {
    return Com_Example_GreeterServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SayHello":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Example_HelloRequest>(),
        responseSerializer: ProtobufSerializer<Com_Example_HelloReply>(),
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? [],
        userFunction: self.sayHello(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Example_GreeterAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Example_GreeterServerInterceptorFactoryProtocol? { get }

  func sayHello(
    request: Com_Example_HelloRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Example_HelloReply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Example_GreeterAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Example_GreeterServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Com_Example_GreeterServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Com_Example_GreeterServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SayHello":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Example_HelloRequest>(),
        responseSerializer: ProtobufSerializer<Com_Example_HelloReply>(),
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? [],
        wrapping: { try await self.sayHello(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Com_Example_GreeterServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'sayHello'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSayHelloInterceptors() -> [ServerInterceptor<Com_Example_HelloRequest, Com_Example_HelloReply>]
}

public enum Com_Example_GreeterServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Greeter",
    fullName: "com.example.Greeter",
    methods: [
      Com_Example_GreeterServerMetadata.Methods.sayHello,
    ]
  )

  public enum Methods {
    public static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/com.example.Greeter/SayHello",
      type: GRPCCallType.unary
    )
  }
}
